[2024-05-24 16:46:33,901][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=5, round_timeout=None)
[2024-05-24 16:46:38,882][flwr][INFO] - Flower VCE: Ray initialized with resources: {'object_store_memory': 939023155.0, 'CPU': 8.0, 'node:127.0.0.1': 1.0, 'memory': 1878046311.0}
[2024-05-24 16:46:38,883][flwr][INFO] - Initializing global parameters
[2024-05-24 16:46:38,884][flwr][INFO] - Requesting initial parameters from one random client
[2024-05-24 16:46:40,943][flwr][INFO] - Received initial parameters from one random client
[2024-05-24 16:46:40,944][flwr][INFO] - Evaluating initial parameters
[2024-05-24 16:46:43,518][flwr][INFO] - initial parameters (loss, other metrics): 181.79405808448792, {'accuracy': 0.1391}
[2024-05-24 16:46:43,522][flwr][INFO] - FL starting
[2024-05-24 16:46:43,523][flwr][DEBUG] - fit_round 1: strategy sampled 10 clients (out of 100)
[2024-05-24 16:46:44,928][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=12120, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 602, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 624, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 456, in ray._raylet.raise_if_dependency_failed
ray.exceptions.RaySystemError: System error: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
traceback: Traceback (most recent call last):
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 309, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 215, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 174, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 164, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
[2024-05-24 16:46:45,002][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=8768, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 602, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 624, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 456, in ray._raylet.raise_if_dependency_failed
ray.exceptions.RaySystemError: System error: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
traceback: Traceback (most recent call last):
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 309, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 215, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 174, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 164, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
[2024-05-24 16:46:45,003][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=5604, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 602, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 624, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 456, in ray._raylet.raise_if_dependency_failed
ray.exceptions.RaySystemError: System error: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
traceback: Traceback (most recent call last):
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 309, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 215, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 174, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 164, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
[2024-05-24 16:46:45,023][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=5604, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 602, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 624, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 456, in ray._raylet.raise_if_dependency_failed
ray.exceptions.RaySystemError: System error: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
traceback: Traceback (most recent call last):
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 309, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 215, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 174, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 164, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
[2024-05-24 16:46:45,027][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=8768, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 602, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 624, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 456, in ray._raylet.raise_if_dependency_failed
ray.exceptions.RaySystemError: System error: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
traceback: Traceback (most recent call last):
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 309, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 215, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 174, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 164, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
[2024-05-24 16:46:47,556][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=2444, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 602, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 624, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 456, in ray._raylet.raise_if_dependency_failed
ray.exceptions.RaySystemError: System error: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 47040000 bytes.
traceback: Traceback (most recent call last):
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 309, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 215, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 174, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 164, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\storage.py", line 240, in _load_from_bytes
    return torch.load(io.BytesIO(b))
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\serialization.py", line 1012, in _legacy_load
    result = unpickler.load()
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\serialization.py", line 953, in persistent_load
    obj = cast(Storage, torch.UntypedStorage(nbytes))
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 47040000 bytes.
[2024-05-24 16:46:47,758][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=1200, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 640, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 644, in ray._raylet.execute_task
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\B00830189\OneDrive - Ulster University\phd\Code\Demos\Flower\FlowerTutorial\client.py", line 48, in fit
    train(self.model, self.trainload, optim, epochs, self.device) # Model no longer has weights sent my the server
  File "C:\Users\B00830189\OneDrive - Ulster University\phd\Code\Demos\Flower\FlowerTutorial\model.py", line 45, in train
    for images, labels in trainloader:
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\utils\data\dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\utils\data\dataloader.py", line 1034, in __init__
    w.start()
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\multiprocessing\reductions.py", line 355, in reduce_storage
    metadata = storage._share_filename_cpu_()
RuntimeError: Couldn't open shared file mapping: <000001E73D111342>, error code: <1455>
[2024-05-24 16:46:48,095][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=11500, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 602, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 624, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 456, in ray._raylet.raise_if_dependency_failed
ray.exceptions.RaySystemError: System error: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 47040000 bytes.
traceback: Traceback (most recent call last):
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 309, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 215, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 174, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\ray\serialization.py", line 164, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\storage.py", line 240, in _load_from_bytes
    return torch.load(io.BytesIO(b))
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\serialization.py", line 1012, in _legacy_load
    result = unpickler.load()
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\serialization.py", line 953, in persistent_load
    obj = cast(Storage, torch.UntypedStorage(nbytes))
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 47040000 bytes.
[2024-05-24 16:46:49,382][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=8216, ip=127.0.0.1)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\multiprocessing\queues.py", line 108, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

[36mray::launch_and_fit()[39m (pid=8216, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 633, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 674, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 640, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 644, in ray._raylet.execute_task
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\B00830189\OneDrive - Ulster University\phd\Code\Demos\Flower\FlowerTutorial\client.py", line 48, in fit
    train(self.model, self.trainload, optim, epochs, self.device) # Model no longer has weights sent my the server
  File "C:\Users\B00830189\OneDrive - Ulster University\phd\Code\Demos\Flower\FlowerTutorial\model.py", line 45, in train
    for images, labels in trainloader:
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\utils\data\dataloader.py", line 1316, in _next_data
    idx, data = self._get_data()
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\utils\data\dataloader.py", line 1282, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\utils\data\dataloader.py", line 1133, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 17888, 14440) exited unexpectedly
[2024-05-24 16:46:52,987][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=8476, ip=127.0.0.1)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\multiprocessing\queues.py", line 108, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

[36mray::launch_and_fit()[39m (pid=8476, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 633, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 674, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 640, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 644, in ray._raylet.execute_task
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\B00830189\OneDrive - Ulster University\phd\Code\Demos\Flower\FlowerTutorial\client.py", line 48, in fit
    train(self.model, self.trainload, optim, epochs, self.device) # Model no longer has weights sent my the server
  File "C:\Users\B00830189\OneDrive - Ulster University\phd\Code\Demos\Flower\FlowerTutorial\model.py", line 45, in train
    for images, labels in trainloader:
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\utils\data\dataloader.py", line 1316, in _next_data
    idx, data = self._get_data()
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\utils\data\dataloader.py", line 1282, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\B00830189\AppData\Local\anaconda3\envs\flower_tutorial\lib\site-packages\torch\utils\data\dataloader.py", line 1133, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 18292, 13316) exited unexpectedly
[2024-05-24 16:46:52,993][flwr][DEBUG] - fit_round 1 received 0 results and 10 failures
[2024-05-24 16:46:55,607][flwr][INFO] - fit progress: (1, 181.79405808448792, {'accuracy': 0.1391}, 12.0903872)
[2024-05-24 16:46:55,614][flwr][DEBUG] - evaluate_round 1: strategy sampled 25 clients (out of 100)
[2024-05-24 16:46:55,992][flwr][DEBUG] - evaluate_round 1 received 0 results and 25 failures
[2024-05-24 16:46:55,993][flwr][DEBUG] - fit_round 2: strategy sampled 10 clients (out of 100)
[2024-05-24 16:46:56,151][flwr][DEBUG] - fit_round 2 received 0 results and 10 failures
[2024-05-24 16:46:58,733][flwr][INFO] - fit progress: (2, 181.79405808448792, {'accuracy': 0.1391}, 15.2111605)
[2024-05-24 16:46:58,734][flwr][DEBUG] - evaluate_round 2: strategy sampled 25 clients (out of 100)
[2024-05-24 16:46:59,167][flwr][DEBUG] - evaluate_round 2 received 0 results and 25 failures
[2024-05-24 16:46:59,168][flwr][DEBUG] - fit_round 3: strategy sampled 10 clients (out of 100)
[2024-05-24 16:46:59,353][flwr][DEBUG] - fit_round 3 received 0 results and 10 failures
[2024-05-24 16:47:01,986][flwr][INFO] - fit progress: (3, 181.79405808448792, {'accuracy': 0.1391}, 18.4698652)
[2024-05-24 16:47:01,993][flwr][DEBUG] - evaluate_round 3: strategy sampled 25 clients (out of 100)
[2024-05-24 16:47:02,360][flwr][DEBUG] - evaluate_round 3 received 0 results and 25 failures
[2024-05-24 16:47:02,361][flwr][DEBUG] - fit_round 4: strategy sampled 10 clients (out of 100)
[2024-05-24 16:47:02,577][flwr][DEBUG] - fit_round 4 received 0 results and 10 failures
[2024-05-24 16:47:05,191][flwr][INFO] - fit progress: (4, 181.79405808448792, {'accuracy': 0.1391}, 21.6705502)
[2024-05-24 16:47:05,194][flwr][DEBUG] - evaluate_round 4: strategy sampled 25 clients (out of 100)
[2024-05-24 16:47:05,558][flwr][DEBUG] - evaluate_round 4 received 0 results and 25 failures
[2024-05-24 16:47:05,560][flwr][DEBUG] - fit_round 5: strategy sampled 10 clients (out of 100)
[2024-05-24 16:47:05,754][flwr][DEBUG] - fit_round 5 received 0 results and 10 failures
[2024-05-24 16:47:08,425][flwr][INFO] - fit progress: (5, 181.79405808448792, {'accuracy': 0.1391}, 24.902896499999997)
[2024-05-24 16:47:08,426][flwr][DEBUG] - evaluate_round 5: strategy sampled 25 clients (out of 100)
[2024-05-24 16:47:08,833][flwr][DEBUG] - evaluate_round 5 received 0 results and 25 failures
[2024-05-24 16:47:08,833][flwr][INFO] - FL finished in 25.311610699999996
[2024-05-24 16:47:08,835][flwr][INFO] - app_fit: losses_distributed []
[2024-05-24 16:47:08,836][flwr][INFO] - app_fit: metrics_distributed_fit {}
[2024-05-24 16:47:08,836][flwr][INFO] - app_fit: metrics_distributed {}
[2024-05-24 16:47:08,836][flwr][INFO] - app_fit: losses_centralized [(0, 181.79405808448792), (1, 181.79405808448792), (2, 181.79405808448792), (3, 181.79405808448792), (4, 181.79405808448792), (5, 181.79405808448792)]
[2024-05-24 16:47:08,836][flwr][INFO] - app_fit: metrics_centralized {'accuracy': [(0, 0.1391), (1, 0.1391), (2, 0.1391), (3, 0.1391), (4, 0.1391), (5, 0.1391)]}
